import {
  SiJavascript,
  SiReact,
  SiTypescript,
  SiWindowsterminal,
  SiPowershell,
  SiAmazonaws,
  SiCloudflare,
  SiFirebase,
  SiGooglecloud,
  SiNetlify,
  SiChakraui,
  SiChartdotjs,
  SiExpress,
  SiNpm,
  SiNodedotjs,
  SiNextdotjs,
  SiReactrouter,
  SiRedux,
  SiSass,
  SiYarn,
  SiVite,
  SiFigma,
  SiPrettier,
  SiJira,
  SiGit,
  SiGithub,
} from "react-icons/si";

export const icons = [
  { name: "JavaScript", icon: SiJavascript },
  { name: "React", icon: SiReact },
  { name: "TypeScript", icon: SiTypescript },
  { name: "Windows Terminal", icon: SiWindowsterminal },
  { name: "PowerShell", icon: SiPowershell },
  { name: "AWS", icon: SiAmazonaws },
  { name: "Cloudflare", icon: SiCloudflare },
  { name: "Firebase", icon: SiFirebase },
  { name: "Google Cloud", icon: SiGooglecloud },
  { name: "Netlify", icon: SiNetlify },
  { name: "Chakra UI", icon: SiChakraui },
  { name: "Chart.js", icon: SiChartdotjs },
  { name: "Context API", icon: SiReact }, // özel ikon yok
  { name: "Express.js", icon: SiExpress },
  { name: "NPM", icon: SiNpm },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "React Router", icon: SiReactrouter },
  { name: "Redux", icon: SiRedux },
  { name: "SASS", icon: SiSass },
  { name: "Yarn", icon: SiYarn },
  { name: "Vite", icon: SiVite },
  { name: "Figma", icon: SiFigma },
  { name: "Prettier", icon: SiPrettier },
  { name: "Jira", icon: SiJira },
  { name: "Git", icon: SiGit },
  { name: "GitHub", icon: SiGithub },
];
